### ISSUE TITLE
Remove keyboard access when hidden

### ISSUE THREAD

**Issue by thomasdigby** [frend/frend.co#10]
https://developer.mozilla.org/en-US/docs/Web/Events/transitionend

Might help, although we'll need to detect if a transition is applied.

Not sure if setting `tabindex="-1"` on each focusable element or `display: none` the parent node is best.

**Comment by thomasdigby** [comment]
Or maybe `visibility: hidden` as per http://heydonworks.com/practical_aria_examples/#hamburger

**Comment by thomasdigby** [comment]
Something similar to https://github.com/EvandroLG/transitionEnd/blob/master/src/transition-end.js to detect transitionEnd event will be handy.

**Comment by thomasdigby** [comment]
@adamduncan Take a wee look taaaa

**Comment by adamduncan** [comment]
Dardicus. Could this toggle a class on the docEl and handle with CSS, instead of setting style objects/looping in JS?

**Comment by thomasdigby** [comment]
It could do, saying that...

It's only setting a single property and it gets called on transitionEnd & panel close so I'm not sure how you'd define the class `[aria-hidden="true"].component-has-transitioned`

**Comment by thomasdigby** [comment]
More research into keyboard access on aria-hidden (expanded?) needed.

**Comment by thomasdigby** [comment]
I'm still unsure about this, I'm leaning towards removing `aria-hidden` & `visibility: hidden;` and adding a different aria-attribute that is still keyboard accessible.

http://www.bettertesting.co.uk/content/?p=1672

**Comment by thomasdigby** [comment]
Added as per https://twitter.com/heydonworks/status/689797482008727552
