### ISSUE TITLE
Determine how to incorporate component skin layer

### ISSUE THREAD

**Issue by adamduncan** [frend/frend.co#12]
Do we bundle this along with Frend's own CSS?

**Comment by thomasdigby** [comment]
I think we both agree the component styles should be different to the site styles.

But if we bundle them with `global.css` we'll need to do a reset on all the site-wide styles already declared. We can set an 'all: unset;' on the `.component-embed` to remove all custom site styles for that block, but that will also overwrite the component styles...

Also, if we want to maintain a consistent look with each component, we'll have to do it by using the component selectors right?

``` scss
.fr-offcanvas,
.fr-tabs {
  background-color: $deeeep-purple;
}
```

Imagine this monstrosity growing with each component created. We'll want (need) to keep the site styles/component styles (and selectors) decoupled, so referencing `.fr-tabs` in `global.css` is a no-go.

Could we add a separate `fr-tabs.style.css` or something similar?

**Comment by thomasdigby** [comment]
Integrate styles as partials within frend.co css/
