### ISSUE TITLE
Move init() calls out of modules

### ISSUE THREAD

**Issue by adamduncan** [frend/frend.co#17]
@thomasdigby I've moved init() call into Tabs public API, and calling from _layouts/component now - whaddya think @thomasdigby? See: https://github.com/frend/frend.co/commit/cef3be9cafb77dd7f4baa217f113cb0d769b4add

Shall we roll this into the others?

**Comment by thomasdigby** [comment]
`init` should be included in the public API for sure.

I'm slightly leaning towards self-initalising the components but happy to go either way.

**Comment by thomasdigby** [comment]
Revert.

**Comment by thomasdigby** [comment]
Can I -1 here?
