### ISSUE TITLE
Add non-js functionality

### ISSUE THREAD

**Issue by thomasdigby** [frend/frend.co#22]
Perhaps the `:target` method will work well as a progressive enhancement.

**Comment by thomasdigby** [comment]
As per [css-tricks.com](https://css-tricks.com/off-canvas-menu-with-css-target/)

**Comment by adamduncan** [comment]
Yeah, that'd be an interesting approach!

**Comment by thomasdigby** [comment]
Thinking about it a little more, I'm not convinced by this approach. We'll need to find a way of progressively enhancing this component but I reckon it could just be shown by default.

The placement of the component (panel/button) is down to the developer, so maintaining an understandable hierarchy in the document should be achievable.

e.g. Placing a navigational off-canvas within the header or just after.

**Comment by thomasdigby** [comment]
Closing this, I don't think we need to mimic the behaviour in CSS. A static panel should work well enough.
