### ISSUE TITLE
Animate panel height

### ISSUE THREAD

**Issue by thomasdigby** [frend/frend.co#28]

**Comment by thomasdigby** [comment]
A couple of things to note from #13e5153:
- Panel has padding removed to correctly set 0 height, an inner is used to pad the contents for now.
- `transitionLength` has to be defined by the user, otherwise we're in `transitionEnd` event hell again
- There's a mini animate on load which we'll need to remove. Not sure how at the moment.

**Comment by adamduncan** [comment]
Merged in with #61 PR. Shout if there's anything I missed.

**Comment by adamduncan** [comment]
@thomasdigby - let's look at that animate on load thing? I guess all components have a bit of flash-of-unstyled...
