### ISSUE TITLE
Add CSS transitions

### ISSUE THREAD

**Issue by NigelOToole** [frend/frend.co#59]
I think adding CSS based transitions to these components would make much more visually appealing. I have added an event listener to the transition end event in the jS and new styles in the CSS that you can see below. This needs to be refactored but gives you a good idea of my thinking. Let me know what you think.

I tried to do a fork of the repo to suggest this but couldnt get the site to run locally, there doesnt seem to be any serve task.

**tabs.js**

```
function _showTab (target, giveFocus = true, firstRun = false) {
        let thisContainer = target.parentNode.parentNode.parentNode;

        let siblingTabs = thisContainer.querySelectorAll(tablistSelector + ' a');
        let siblingTabpanels = thisContainer.querySelectorAll(tabpanelSelector);
        let currentTab = thisContainer.querySelectorAll(tabpanelSelector + '.is-active')[0];
        let nextTab = doc.getElementById(target.getAttribute('aria-controls'));
        let tabTransitionDuration = parseFloat(getComputedStyle(siblingTabpanels[0])['transitionDuration']);

        // set inactives on tab links
        siblingTabs.forEach((tab) => {
            tab.setAttribute('tabindex', -1);
            tab.removeAttribute('aria-selected');
        });

        target.setAttribute('tabindex', 0);
        target.setAttribute('aria-selected', 'true');
        if (giveFocus) target.focus();


        // setup tab panels on first run
        if(firstRun) {
            siblingTabpanels.forEach((tabpanel) => {
                tabpanel.setAttribute('aria-hidden', 'true');           
                tabpanel.classList.add('is-inactive');      
            });

            nextTab.removeAttribute('aria-hidden');
            nextTab.classList.add('is-active');
            nextTab.classList.remove('is-inactive');
        }

        // Change tab panels
        if(!firstRun) {

            if(tabTransitionDuration > 0) {
                currentTab.classList.add('is-anim');

                currentTab.addEventListener('transitionend', function _func() {

                    // transition the currently open tab
                    currentTab.removeEventListener('transitionend', _func);

                    currentTab.classList.remove('is-active', 'is-anim');
                    currentTab.classList.add('is-inactive');
                    currentTab.setAttribute('aria-hidden', 'true');

                    // transition next tab
                    nextTab.classList.add('is-anim');

                    setTimeout(function() {
                        nextTab.classList.remove('is-inactive', 'is-anim');
                        nextTab.classList.add('is-active');
                        nextTab.removeAttribute('aria-hidden');
                    }, 0);
                });

            }
            else
            {
                currentTab.classList.remove('is-active');
                currentTab.setAttribute('aria-hidden', 'true');

                nextTab.classList.add('is-active');
                nextTab.removeAttribute('aria-hidden');
            }

        }

    }
```

**CSS** - I removed the [aria-hidden="true"] targeting as that interfered with the CSS specificity.

```

.fr-tabs__panel {
  opacity: 1;
  transition: opacity 1s;

  &.is-inactive, &.is-anim {
    opacity: 0;
  }
  &.is-inactive {
    display: none;
  }
  &.is-anim {
    display: block;
  }
}
```

**Comment by adamduncan** [comment]
Hi @NigelOToole, thanks for getting back to us. Funnily enough, @thomasdigby and I have had a _lot_ of discussions around the balance of function and style for these components.

There is something to be said for making them visually appealing. At the same time, if our primary focus is on them being accessible, it feels beneficial to omit assumptions about their visual styling.

Do you think this is something that could be tackled by developers using the CSS in their own implementations? I'm happy to have a go at achieving a similar outcome using the functionality as it currently exists?

**Comment by NigelOToole** [comment]
Hi @adamduncan, I agree that the focus should not be on the visual styling of these components. However I think that having a transition between states is something that is expected on most websites. So while these transitions don't need to be on the components by default I think changing the code to facilitate adding these transitions would make sense. Perhaps you could expose component events to allow developers access to these without changing the source code e.g. 

```
myTabs.on('opening', function (e) {
...
})
```

**Comment by adamduncan** [comment]
Yeah, callbacks would be a nice addition. We've explored animation on the [accordion fix branch](https://github.com/frend/frend.co/tree/fix/28-animate-accordion-height). This takes the approach of defining a duration parameter and setting a timeout on events until the animation is complete. This might be simplified by using a `transitionend` handler?

Here's a quick [example of animating transitions using CSS](http://codepen.io/adamduncan/pen/oxpNyz?editors=0100) alone, an alternative to modifying the JS. There are considerations (like differing height of the panels), which make animation slightly more complicated. An option could be to animate the contents, instead of the panels themselves. It lacks the ability to cross-fade between panels, but it's a concise alternative.

Worth us opening a ticket for exposing event callbacks, to offer a bit more flexibility, @NigelOToole?

**Comment by adamduncan** [comment]
Also, getting the site running locally should just require the jekyll gem, an `npm install` from the cloned directory and a `jekyll serve`. `gulp watch` will run the component CSS/JS tasks as you build. Drop me a line on [Twitter](https://twitter.com/duncanadam) if need be and we can make sure the details are added to the docs.

**Comment by NigelOToole** [comment]
I think using `transitionend` would be a more flexible solution as you would only need to adjust the timings in the CSS as needed and not change the JS. I think you are on the right path with the accordion by getting the height and setting it inline. If `transitionend` can replace the timeouts I think that would be the most elegant solution

Your example of animating using CSS works well but would it be as performant with many child elements in the tabs? 

I think exposing callback events would definitely be worth doing, giving developers more control would make the components more appealing.

I have gotten the site up and running thanks, may be worth adding more info to the docs as I wasnt familiar with Jekyll. You need to install the jekyll gem and jekyll-redirect-from gem. 

I have also been playing with a responsive tabs component that changes to an accordion on small screens, it has an external dependancy on enquire.js for the responsive states. Not sure if this is getting too far from your original idea but I can add the code to my fork of the repo if you would like a look.

**Comment by thomasdigby** [comment]
Hey Nigel, we're definitely going to look at integrating events into our component API's, it just didn't make the cut for our initial mvp. We're also looking at updating our docs across the site so we'll add the relevant Jekyll information then.

The `transitionend` event was something we looked at but the overhead for cross-browser variations turned us off the idea initially. Saying that, it seems like an ideal method of working with transition timings (certainly better than the `timeout` we currently implement) so we'll look into it again.

We'd certainly like to look at your tabs-to-accordion component, can you work it into your fork? We still need to properly define the scope for frend so we're open to hearing about ideas for components.

We'll let you know when we plan to integrate these changes. Thanks again for the feedback!

**Comment by NigelOToole** [comment]
That all sounds good, I look forward to seeing future developments.

I have added my responsive tabs component to my fork of the repo, please have a look and let me know what you think as I would appreciate your input. Thanks.

**Comment by adamduncan** [comment]
Hey @NigelOToole, just coming back to a few of the points you've raised here.

We've got a [ticket](https://github.com/frend/frend.co/issues/70)/[branch](https://github.com/frend/frend.co/tree/enhancement/event-callbacks) open to tackle component event callbacks. Would be great to get any feedback over there. Once this has been implemented, it will give authors a chance to catch events and, like you say, add transitions etc.

Optimising the use of `transitionend` is still something we should look into, as a way of improving the need for authors to manage timing across CSS and JS. We've been playing with some helper utils across the components (e.g. `_closest()`), so adding a similar transitionend prefixer solution would mean we can drop the `transitionLength` param from the Accordion API.

Docs have been updated with Jekyll info, hopefully that helps other users in future.

The tabs-to-accordion component looks like a good progression from the original. It feels like it might be a little above and beyond the scope of the Frend collection, but it's a great place to point people if they're chasing that behaviour. Thanks again for that.

**Comment by notoole-vccp** [comment]
Hey @adamduncan the work on callbacks looks good, I look forward to seeing it implemented across the components. Also glad to see you are looking into using `transitionend` as I think this will be a great enhancement. I understand the tabs-to-accordion component is out of the scope of the project but it was a fun project to tackle. Looking forward to seeing how Frend progresses.

**Comment by adamduncan** [comment]
Thanks again, @notoole-vccp. We've had an inital play with event callback restructure of JS, so we'll drop you a line when they're ready for some feedback!
