### ISSUE TITLE
Build simple tabs component

### ISSUE THREAD

**Issue by thomasdigby** [frend/frend.co#6]
Create tabs component (in frend.co for now) as a module to integrate with the frend JS, include .scss with separate style/function partials.

**Comment by adamduncan** [comment]
Done, but needs cleaning up and additional comments where necessary

**Comment by thomasdigby** [comment]
Has this been cleaned up enough? Let's close if so.

**Comment by adamduncan** [comment]
Yep, no longer required by the site itself. Closing
