### ISSUE TITLE
Tooltip not dismissing on touch off - iOS9

### ISSUE THREAD

**Issue by thomasdigby** [frend/frend.co#62]
Working ok on Android 6, iOS might not be handling the document click events in the same way.

**Comment by adamduncan** [comment]
From memory, iOS won't `blur` an element that had focus, unless you're giving focus to something else. Worth doing some digging around on why this is. 

Is clicking on the tooltip toggle a second time to dismiss it enough?

**Comment by thomasdigby** [comment]
The `click` events on the `document` weren't firing on iOS so I added `touchstart` and it's now working. Might be a little heavy handed so let's look into improving it in a future update.
