### ISSUE TITLE
Remove NodeList.prototype in favour of querySelectorAll helper function

### ISSUE THREAD

**Issue by adamduncan** [frend/frend.co#64]
Let's utilise a helper function in the components, instead of reassigning NodeList.prototype to Array.prototype. Similar to [Bliss's $$()](http://blissfuljs.com/docs.html#fn-$$)?

**Comment by thomasdigby** [comment]
Initial roll-out in https://github.com/frend/frend.co/tree/enhancement/update-nodelist-prototype

Test test test!

**Comment by thomasdigby** [comment]
#82

**Comment by adamduncan** [comment]
Good stuff, Tom!
