### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by scottaohara** [frend/frend.co#65]
Trying to tab through the [tool tip component](http://frend.co/components/tooltip/) I found that I was unable to tab onto the generated tool tip buttons with Firefox (46.0.1 on OSX).  

(As an aside, I know FireFox follows default OSX system settings and limits what can be focused, but I have the system setting updated to allow for all focusable elements to be tabbed to via keyboard controls, so I know that's not the issue here)

Testing with Safari and Chrome, I was able to tab onto and activate the tool tips as expected.

**Comment by thomasdigby** [comment]
Thanks @scottaohara, it probably has to do with the method to append the new buttons to the DOM. I'll take a look shortly.

**Comment by thomasdigby** [comment]
Hi @scottaohara, I updated my local OSX settings to match yours and I can't replicate your issue. I've pushed an update to the frend.co site to add `:focus` states, can you confirm again if they're not working?

**Comment by scottaohara** [comment]
Interesting.  They're definitely working now, but it definitely wasn't just a focus state styling issue before.

Regardless, thank you for taking the time to check this out
