### ISSUE TITLE
Documentation: List Browser Support

### ISSUE THREAD

**Issue by dnwhte** [frend/frend.co#79]
It'd be really helpful if there was a list of browsers/devices supported.

**Comment by adamduncan** [comment]
Great point, @danwhite85! We should do a per-component browser support list, right before the References. We'll get them in asap! Thanks.

**Comment by adamduncan** [comment]
@thomasdigby, it's super helpful when libraries like [these](https://github.com/callmecavs/layzr.js#browser-support) mention the APIs/methods that result in the component dropping off the support list. Would imagine ours would primarily be `classList` or the usual [mustard cutting](http://responsivenews.co.uk/post/18948466399/cutting-the-mustard) stuff.

**Comment by adamduncan** [comment]
Added with #83. Re-open if more detail needed.
